name: 🐛 Bug Report
description: 提交 Bug
labels: ["bug"]
assignees:
  - your-username
body:
  - type: input
    id: summary
    attributes:
      label: "简要描述"
      placeholder: "请输入问题概述"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "详细描述"
      placeholder: "请详细描述问题"
    validations:
      required: true
